app1:
    build: ./app
    links:
        - master:rs
    ports:
        - "3001:3000"

master:
  image: redis:4.0.1
  ports:
        - "6379"

slave1:
  image: redis:4.0.1
  command: redis-server --slaveof rs 6379
  links:
    - master:rs

sentinel1:
  build: sentinel
  environment:
    - SENTINEL_DOWN_AFTER=5000
    - SENTINEL_FAILOVER=5000
  links:
    - master:rs
    - slave1

