app1:
    build: ./app
    links:
        - redis-sentinel1:rs1
        - redis-sentinel2:rs2
        - redis-sentinel3:rs3
    ports:
        - "3001:3000"

redis-master:
  image: redis:4.0.1
  ports:
        - "6379"

redis-slave1:
  image: redis:4.0.1
  command: redis-server --slaveof rs 6379
  links:
    - redis-master:rs

redis-sentinel1:
  build: sentinel
  links:
    - redis-master:rs

redis-sentinel2:
  build: sentinel
  links:
    - redis-master:rs

redis-sentinel3:
  build: sentinel
  links:
    - redis-master:rs

